export const REGISTER_TICKER = 'REGISTER_TICKER';
export const UNREGISTER_TICKER = 'UNREGISTER_TICKER';
export const TICKER_UPDATE = 'TICKER_UPDATE';
export const GET_TICKER_STATE = 'GET_TICKER_STATE';
export const TICKER_INTERNAL_STATE_CHANGE = 'TICKER_INTERNAL_STATE_CHANGE';
